[package]
name = "c-rt"
version = "0.1.0"
edition = "2021"
authors = ["4lDO2 <4lDO2@protonmail.com>"]
license = "MIT"
description = "C runtime for relibc"

[lib]
path = "src/lib.rs"

[dependencies]
relibc = { path = "../", default-features = false }

[features]
default = []
